version: '3.6'
services:
  calculator:
    container_name: container_2
    image: kaviuln/source_2_image
    ports:
      - 3001:3001
    networks:
      - kav_network
    restart: unless-stopped
    healthcheck:
     test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
     interval: 60s
     retries: 5
     start_period: 20s
     timeout: 10s
  
  db:
    container_name: container_1
    image: kaviuln/source_1_image
    ports:
      - 1370:1334
    networks:
      - kav_network
    restart: unless-stopped
    healthcheck:
     test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
     interval: 60s
     retries: 5
     start_period: 20s
     timeout: 10s

networks:
  kav_network:
    external: true
